# Generated by Django 6.0.3 on 2026-03-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='static/img/default.jpg', upload_to='profile_pictures'),
        ),
    ]
